appName: MyRecipe
logLevel: 0 # DEBUG

app:
  paths:
    voice: 'voice_msgs'

db:
  name: recipes
  user: bot_recipe_usr
  pass: nM21!qnPk9tG%21
  host: localhost
  port: 27017

tg:
  key: '1284815731:AAG_e0bCH_V2S_-bK5aW3nW1dNAwLMhTSGo'

chat:
  state:
    'FIRST_CHOICE': 0
    'NEW_RECIPE': 10
    'SEARCH_RECIPE': 20
    'NEW_RECIPE_COMPONENTS': 40
    'NEW_RECIPE_DESCRIPTION': 50
    'NEW_RECIPE_TAGS': 60
    'NEW_RECIPE_IS_SEARCHABLE': 70
    'NEW_RECIPE_CONFIRMATION': 80
    'BROWSE_MY_RECIPES': 90
    'CHOOSE_RECIPE': 100
    'CHOOSE_SEARCH_RESULTS': 110
    'LIKE_RECIPE': 120